# ErgoDox EZ keymap for keymap-drawer
# Generate SVG: hey ergodox-draw (or uvx --from keymap-drawer keymap draw ...)
# Oryx: https://configure.zsa.io/ergodox-ez/layouts/wagdn/qmvNyL
#
# NOTE: SVG generation requires QMK setup. Run `qmk setup` first, then:
#   hey ergodox-draw
#
# This YAML serves as human-readable layer documentation regardless.

layout:
  # Use local QMK info.json after `qmk setup`
  qmk_info_json: ~/qmk_firmware/keyboards/zsa/ergodox_ez/info.json
  layout_name: LAYOUT_ergodox_pretty

layers:
  Base:
    - ["`", "1", "2", "3", "4", "5", "-", "", "=", "6", "7", "8", "9", "0", Bksp]
    - [Tab, Q, W, E, R, T, PrtSc, "", "(", Y, U, I, O, P, '\']
    - [{ t: Esc, h: Ctl }, A, S, D, F, G, "", "", "", H, J, K, L, ";", "'"]
    - [Shift, Z, X, C, V, B, Del, "", ")", N, M, ",", ".", "/", Shift]
    - [Ctrl, Alt, "", Home, End, "", "", "", "", "[", "]", "{", "}", Ctrl]
    - ["", "", "", "", "", { t: TT, h: L2 }, { t: TT, h: L3 }, VolUp, Mute, "", "", "", "", ""]
    - ["", "", "", "", "", "", Gui, VolDn, "", "", "", "", "", ""]
    - [
        "",
        "",
        "",
        "",
        Space,
        { t: "", h: L1 },
        { t: Esc, h: Alt },
        RGui,
        { t: Bksp, h: L1 },
        Enter,
        "",
        "",
        "",
        "",
      ]

  Symbols:
    - [Esc, F1, F2, F3, F4, F5, "", "", "", F6, F7, F8, F9, F10, Bksp]
    - ["", "!", "@", "#", "$", "%", Pause, "", "[", "^", "&", "*", "(", ")", "|"]
    - ["", "!", "@", "#", "$", "%", "", "", "", Left, Down, Up, Right, ":", '"']
    - ["", "1", "2", "3", "4", "5", Bksp, "", "]", "6", "7", "8", "9", "0", Shift]
    - ["", "", "", PgUp, PgDn, "", "", "", "", Home, End, "", Alt, Ctrl]
    - ["", "", "", "", "", Prev, Next, Prev, Next, "", "", "", "", ""]
    - ["", "", "", "", "", "", Play, Play, "", "", "", "", "", ""]
    - ["", "", "", "", "", "", "", "", "", "", "", "", "", ""]

  Numpad:
    - ["", F1, F2, F3, F4, F5, "", "", "", "^", "&", "%", "$", "", ""]
    - ["", F6, F7, F8, F9, F10, "", "", "(", Up, "7", "8", "9", "-", ""]
    - ["", F11, F12, F13, F14, F15, "", "", "", Down, "4", "5", "6", "+", ""]
    - ["", F16, F17, F18, F19, F20, "", "", ")", "=", "1", "2", "3", "*", ""]
    - ["", "", "", "", "", "", "", "", "", "0", ".", ",", "/", ""]
    - ["", "", "", "", "", "", "", "", "", "", "", "", "", ""]
    - ["", "", "", "", "", "", "", "", "", "", "", "", "", ""]
    - ["", "", "", "", "", "", "", "", "", "", "", "", "", ""]

  Mouse:
    - ["", "", "", "", "", "", "", Boot, "", "", "", "", "", "", ""]
    - ["", "", WhlL, MsUp, WhlR, WhlUp, "", "", "", "", "", Up, "", "", ""]
    - [LED, "", MsLft, MsDn, MsRgt, WhlDn, "", "", "", "", Left, Down, Right, "", Enter]
    - [RGB, Br-, Br+, "", Spd-, Spd+, Esc, "", "", "", "", "", "", "", Shift]
    - ["", "", "", "", "", "", "", "", "", "", "", "", Alt, Ctrl]
    - ["", "", "", "", "", "", "", "", "", "", "", "", "", ""]
    - ["", "", "", "", "", "", "", "", "", "", "", "", "", ""]
    - ["", "", "", "", Btn1, Btn2, Btn3, Gui, "", Space, "", "", "", ""]
